---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi
  namespace: tenant2-extract
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
      - name: flaskapi
        image: gagangiri94/flask-api:1.0.3
        resources:
          limits: 
            memory: 200Mi
            cpu: 0.5
          requests:
            memory: 100Mi
            cpu: 0.2               
        ports:
          - containerPort: 5000
        env:
        - name: db_root_password
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: db_name
          value: wordpress
        - name: MYSQL_SERVICE_HOST
          value: wordpress-mysql.tenant1  
        - name: MYSQL_SERVICE_PORT
          value: "3306"
              

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: tenant2-extract
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer